#This compose file adds BookStack https://www.bookstackapp.com to your stack
version: '3.5'
services:
  reverse-proxy:
    networks:
      - bookstack
  mail-relay:
    networks:
      - bookstack
  bookstack:
    image: solidnerd/bookstack:latest
    container_name: bookstack
    environment:
      - DB_DATABASE=bookstack
      - DB_USERNAME=${BOOKSTACK_DB_USERNAME:?Please copy template.env to .env and provide provide a value for BOOKSTACK_DB_USERNAME}
      - DB_PASSWORD=${BOOKSTACK_DB_PASSWORD:?Please copy template.env to .env and provide provide a value for BOOKSTACK_DB_PASSWORD}
      - DB_HOST=bookstack-db
      - MAIL_HOST=mail-relay
      - MAIL_PORT=25
      - MAIL_FROM=${FROM_ADDRESS:?Please copy template.env to .env and provide provide a value for FROM_ADDRESS}
      - APP_URL=https://${BOOKSTACK_DOMAIN:?Please copy template.env to .env and provide provide a value for BOOKSTACK_DOMAIN}
    volumes:
      - bookstack-storage:/var/www/bookstack/public/storage
      - bookstack-uploads:/var/www/bookstack/public/uploads
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:{BOOKSTACK_DOMAIN:?Please copy template.env to .env and provide provide a value for BOOKSTACK_DOMAIN}
      - traefik.docker.network=bookstack
      - traefik.default.protocol=http
      - com.ouroboros.enable=true
    networks:
      - bookstack
    restart: unless-stopped
    depends_on:
      - bookstack-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://bookstack || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s

  bookstack-db:
    image: mariadb:latest
    container_name: bookstack-db
    environment:
      - MYSQL_DATABASE=bookstack
      - MYSQL_USER=${BOOKSTACK_DB_USERNAME}
      - MYSQL_PASSWORD=${BOOKSTACK_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_DB_ROOT_PASSWORD:?Please copy template.env to .env and provide provide a value for BOOKSTACK_DB_ROOT_PASSWORD}
    volumes:
      - "bookstack-database-data:/var/lib/mysql"
    labels:
      - traefik.enable=false
      - com.ouroboros.enable=true
    restart: unless-stopped
    networks:
      - bookstack
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u $$MYSQL_USER --password=$$MYSQL_PASSWORD ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  bookstack:

volumes:
  bookstack-storage:
  bookstack-uploads:
  bookstack-database-data:


