#This adds Mastodon https://mastodon.social/about to your stack
#I used volumes here, but you might want to use mount binds to a location on a large
#drive instead.  In that case, change the value before : in each volumes section to a
#directory you wish to store the data.  You must run `chown 991 mastodon-assets
#mastodon-system mastodon-packs` at the command line, replacing the vales of
#mastodon-assets, mastodon-system, and mastodon-packs to the directories you replaced
#them with for Mastodon to build its assets correctly, otherwise build will fail and
#the server will return HTTP error 500 when you connect to it.  Make sure to delete
#the entire volumes: section at the bottom of this file if you use mount binds,
#otherwise named volumes will be created but not be used.
####################################################################################
#make sure to edit values in configs/mastodon.env                                  #
#there are mandatory configuration items in this file.  instructions in comments   #
#  ****Please note: ElasticSearch is storage and memory intensive.  You also       #
#      probably don't need it for a home server instance of Mastodon.  Only        #
#      enable it if you're sure you want it and your system can handle it.         #
#      You must run the following command before starting mastodon-elasticsearch   #
#      sudo sysctl -w vm.max_mapp_count=262144                                     #
#      You will need to edit /etc/sysctl.conf on your host and add the following:  #
#      vm.max_map_count=262144                                                     #
#      to make this change permanent.  Elasticsearch's data directory must         #
#      also be writable by the user who launches the container for some reason     #
####################################################################################

version: '3.5'
services:
  reverse-proxy:
    networks:
      - mastodon-external
  mail-relay:
    networks:
      - mastodon-internal
      - mastodon-external
  mastodon-db:
    restart: unless-stopped
    container_name: mastodon-db
    image: postgres:latest
    networks:
      - mastodon-internal
    volumes:
      - mastodon-db:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
      - com.ouroboros.enable=false #postgres needs a manual database migration on major version updates
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] #checking local connectivity
      interval: 10s
      timeout: 5s
      retries: 5

  mastodon-redis:
    restart: unless-stopped
    container_name: mastodon-redis
    image: redis:latest
    networks:
      - mastodon-internal
    labels:
      - "traefik.enable=false"
      - "com.ouroboros.enable=true"
    volumes:
      - mastodon-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

#  mastodon-elasticsearch:
#    restart: unless-stopped
#    image: elasticsearch:6.6.0
#    container_name: mastodon-elasticsearch
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    networks:
#      - mastodon-internal
#    expose:
#      - "9200"
#    volumes:
#      - mastodon-elasticsearch:/usr/share/elasticsearch/data
#    labels:
#      - "traefik.enable=false"
#      - "com.ouroboros.enable=true"
#    healthcheck:
#      test: ["CMD-SHELL", "curl --silent --fail mastodon-elasticsearch:9200/_cluster/health || exit 1"]

  mastodon-web:
    container_name: mastodon-web
    image: tootsuite/mastodon:v2.7.1
    restart: unless-stopped
    env_file: ./configs/mastodon.env
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - mastodon-external
      - mastodon-internal
    expose:
      - "3000"
    depends_on:
      - mastodon-db
      - mastodon-redis
 #     - mastodon-elasticsearch
    volumes:
      - mastodon-assets:/mastodon/public/assets
      - mastodon-packs:/mastodon/public/packs
      - mastodon-system:/mastodon/public/system
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${MASTODON_DOMAIN:?Please copy template.env to .env and provide provide a value for MASTODON_DOMAIN}
      - traefik.docker.network=mastodon-external
      - com.ouroboros.enable=true
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --no-proxy mastodon-web:3000/api/v1/instance || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 15s

  mastodon-streaming:
    container_name: mastodon-streaming
    image: tootsuite/mastodon:v2.7.1
    restart: unless-stopped
    env_file: ./configs/mastodon.env
    command: yarn start
    networks:
      - mastodon-external
      - mastodon-internal
    expose:
      - "4000"
    depends_on:
      - mastodon-db
      - mastodon-redis
    labels:
      - traefik.enable=true
      - traefik.port=4000
      - traefik.docker.network=mastodon-external
      - traefik.frontend.rule=Host:${MASTODON_DOMAIN};PathPrefixStrip:/api/v1/streaming
      - com.ouroboros.enable=true
    volumes:
      - mastodon-assets:/mastodon/public/assets
      - mastodon-packs:/mastodon/public/packs
      - mastodon-system:/mastodon/public/system
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --header 'x-forwarded-proto: https' --no-proxy mastodon-streaming:4000/api/v1/streaming/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 15s

  mastodon-sidekiq:
    container_name: mastodon-sidekiq
    image: tootsuite/mastodon:v2.7.1
    restart: unless-stopped
    env_file: ./configs/mastodon.env
    command: bundle exec sidekiq
    depends_on:
      - mastodon-db
      - mastodon-redis
    networks:
      - mastodon-external
      - mastodon-internal
    volumes:
      - mastodon-assets:/mastodon/public/assets
      - mastodon-packs:/mastodon/public/packs
      - mastodon-system:/mastodon/public/system
    labels:
      - traefik.enable=false
      - com.ouroboros.enable=true

networks:
  mastodon-external:
  mastodon-internal:
    internal: true

volumes:
  mastodon-assets:
  mastodon-packs:
  mastodon-system:
  mastodon-db:
  #mastodon-elasticsearch:
  mastodon-redis: