#This compose file adds Piwigo, a photo collection app http://piwigo.org to your stack
version: '3.5'
services:
  reverse-proxy:
    networks:
      - piwigo
  mail-relay:
    networks:
      - piwigo
  piwigo:
    image: linuxserver/piwigo:latest
    container_name: piwigo
    volumes:
      - piwigo-config:/config
      - piwigo-pictures:/pictures
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - PGID=${UID}
      - PUID=${UID}
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${PIWIGO_DOMAIN:?Please copy template.env to .env and provide provide a value for PIWIGO_DOMAIN}"
      - "traefik.docker.network=piwigo"
      - "traefik.default.protocol=http"
      - "com.ouroboros.enable=true"
    networks:
      - piwigo
    restart: unless-stopped
    depends_on:
      - piwigo-db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://piwigo || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 15s

  piwigo-db:
    image: mariadb:5.5.60 #the community extension requires mariadb 5 for now
    container_name: piwigo-db
    hostname: piwigo-db
    environment:
      MYSQL_DATABASE: piwigo
      MYSQL_USER: ${PIWIGO_DB_USERNAME:-piwigo}
      MYSQL_PASSWORD: ${PIWIGO_DB_PASSWORD:?Please copy template.env to .env and provide provide a value for PIWIGO_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PIWIGO_DB_ROOT_PASSWORD:-?Please copy template.env to .env and provide provide a value for PIWIGO_DB_ROOT_PASSWORD}
    volumes:
      - piwigo-database:/var/lib/mysql
    labels:
      - "traefik.enable=false"
      - "com.ouroboros.enable=true"
    restart: unless-stopped
    networks:
      - piwigo
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u $$MYSQL_USER --password=$$MYSQL_PASSWORD ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  piwigo:

volumes:
  piwigo-config:
  piwigo-pictures:
  piwigo-database:
