#This adds NextCloud https://nextcloud.com to your stack
#I highly recommend that you substitute bind mounts for volumes for volumes
#in this service to ensure they are on a device with ample storeage for your
#NextCloud data.  To utilize Collabora for document editing, after starting,
#log into NextCloud and:
#1 Go to the Apps section and choose "Office & text"
#2 Install the "Collabora Online app"
#3 Admin -> Collabora Online -> Specify the server you have setup below
#(e.g. "https://office.yourDynamicDomain.duckdns.org")
#Your Collabora's admin settings can be accessed at
#https://office.yourDynamicDomain.duckdns.org/loleaflet/dist/admin/admin.html
version: '3.5'
services:
  reverse-proxy:
    networks:
      - nextcloud

  mail-relay:
    networks:
      - nextcloud

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${NEXTCLOUD_DB_USERNAME:-nextcloud}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD:?Please copy template.env to .env and provide provide a value for NEXTCLOUD_DB_PASSWORD}
      - MYSQL_HOST=nextcloud-db
    volumes:
      - nextcloud-html:/var/www/html
      - nextcloud-ssl:/etc/ssl
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:${NEXTCLOUD_DOMAIN:?Please copy template.env to .env and provide provide a value for NEXTCLOUD_DOMAIN}
      - traefik.nextcloud-dav.frontend.rule=Host:${NEXTCLOUD_DOMAIN};Path:/.well-known/carddav,/.well-known/caldav;ReplacePath:/remote.php/dav
      - traefik.nextcloud-webfinger.frontend.rule=Host:${NEXTCLOUD_DOMAIN};Path:/.well-known/webfinger;ReplacePath:/public.php?service=webfinger
      - traefik.docker.network=nextcloud
      - traefik.frontend.headers.STSSeconds=15552000
      - com.ouroboros.enable=true
    networks:
      - nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - office
#    healthcheck:
#      test: ["CMD-SHELL", "curl -f http://nextcloud || exit 1"]
#      interval: 1m30s
#      timeout: 10s
#      retries: 5
#      start_period: 15s

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${NEXTCLOUD_DB_USERNAME:-nextcloud}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD:?Please copy template.env to .env and provide provide a value for NEXTCLOUD_DB_ROOT_PASSWORD}
    volumes:
      - nextcloud-database:/var/lib/mysql
    labels:
      - "traefik.enable=false"
      - "com.ouroboros.enable=true"
    restart: unless-stopped
    networks:
      - nextcloud
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u $$MYSQL_USER --password=$$MYSQL_PASSWORD ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  office:
    image: collabora/code:latest
    container_name: office
    environment:
      - domain=${NEXTCLOUD_DOMAIN:?Please copy template.env to .env and provide provide a value for NEXTCLOUD_DOMAIN}
      - username=${COLLABORA_ADMIN_USERNAME:?Please copy template.env to .env and provide provide a value for COLLABORA_ADMIN_USERNAME}
      - password=${COLLABORA_ADMIN_PASSWORD:?Please copy template.env to .env and provide provide a value for COLLABORA_ADMIN_PASSWORD}
      - server_name=${COLLABORA_OFFICE_DOMAIN:?Please copy template.env to .env and provide provide a value for COLLABORA_OFFICE_DOMAIN}
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
      - dictionaries=en_US
    labels:
      - traefik.enable=true
      - traefik.web.frontend.rule=Host:${COLLABORA_OFFICE_DOMAIN:?Please copy template.env to .env and provide provide a value for COLLABORA_OFFICE_DOMAIN}
      - traefik.port=9980
      - traefik.protocol=http
      - traefik.docker.network=nextcloud
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.forceSTSHeader=true
      - traefik.frontend.headers.STSSeconds=15552000
      - traefik.frontend.headers.STSIncludeSubdomains=true
      - com.ouroboros.enable=true
    restart: unless-stopped
    networks:
      - nextcloud
    cap_add:
      - MKNOD #required to function properly
    expose:
      - "9980"
    tty: true

networks:
  nextcloud:

#Don't forget to remove this section if you substitute bind mounts for volumes above!
volumes:
  nextcloud-html:
  nextcloud-ssl:
  nextcloud-database:

